name: shopping_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  get: 4.3.8
  pinput: 1.2.2
  velocity_x: 3.3.0
  flutter_spinkit: 5.1.0
  google_fonts: 2.1.0
  cached_network_image: 3.1.0+1
  firebase_auth: 3.2.0
  cloud_firestore: 3.1.0
  firebase_core: 1.10.0
  firebase_crashlytics: 2.3.0
  firebase_dynamic_links: 3.0.1
  image_picker: 0.8.4+4
  infinite_scroll_pagination: 3.1.0
  google_sign_in: 5.2.1
  firebase_database: 8.2.0
  custom_utils: 
    git: https://github.com/imsamgarg/custom_utils.git
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  lints: 1.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
  uses-material-design: true

flutter_assets: 
  assets_path: assets/
  output_path: lib/app/core/values
  finename: assets.dart

