name: shopping_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.15.0 <3.0.0'

dependencies: 
  get: ^4.5.1
  pinput: 1.2.2
  velocity_x: 3.3.0
  flutter_spinkit: 5.1.0
  path_provider: ^2.0.7
  google_fonts: 2.1.0
  cached_network_image: ^3.2.0
  firebase_auth: ^3.3.3
  cloud_firestore: ^3.1.4
  firebase_core: ^1.10.5
  firebase_dynamic_links: ^4.0.2
  image_picker: 0.8.4+4
  infinite_scroll_pagination: 3.1.0
  google_sign_in: 5.2.1
  firebase_database: ^9.0.2
  firebase_app_check: 0.0.6+2
  flutter_slidable: 1.1.0
  share_plus: 3.0.4
  firebase_storage: 10.2.4
  firebase_image: 
    path: ../firebase_image
  custom_utils: 
    git: https://github.com/imsamgarg/custom_utils.git
  flutter: 
    sdk: flutter
  razorpay_flutter: ^1.2.7

dev_dependencies: 
  flutter_lints: ^1.0.0
  lints: 1.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
  uses-material-design: true

flutter_assets: 
  assets_path: assets/
  output_path: lib/app/core/values
  finename: assets.dart

